services:
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0  # 允许外部网络访问
      - xpack.security.enabled=false  # 禁用 X-Pack 安全认证
      - ES_JAVA_OPTS=-Xms1g -Xmx1g  # 将最小和最大堆内存设置为 1GB
    mem_limit: 2g  # 设置内存上限为 2GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data  # 持久化数据存储
    ports:
      - "9200:9200"  # 映射 9200 端口用于外部访问
      - "9300:9300"  # 映射 9300 端口用于节点间通信
    networks:
      - elastic

  kibana:
    image: kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # 指向 Elasticsearch 服务
    ports:
      - "5601:5601"  # 映射 5601 端口用于外部访问 Kibana
    networks:
      - elastic

volumes:
  esdata:
    driver: local  # 使用本地卷来持久化 Elasticsearch 数据

networks:
  elastic:
    driver: bridge  # 使用默认的 bridge 网络